const mongoose = require("mongoose");
require("dotenv").config({ path: ".env.local" });

const playerSchema = new mongoose.Schema({
  playerId: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  team: { type: String, required: true },
  teamCode: String,
  position: { type: String, required: true },
  nationality: { type: String, required: true },
  height: { type: Number, required: true },
  imageUrl: String,
  active: { type: Boolean, default: true },
});

const Player = mongoose.models.Player || mongoose.model("Player", playerSchema);

const players = [
  // ANADOLU EFES
  { playerId: "larkin-shane", name: "Shane Larkin", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "PG", nationality: "Turkey", height: 180 },
  { playerId: "beaubois-rodrigue", name: "Rodrigue Beaubois", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "PG", nationality: "France", height: 188 },
  { playerId: "loyd-jordan", name: "Jordan Loyd", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "SG", nationality: "United States", height: 196 },
  { playerId: "lee-saben", name: "Saben Lee", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "PG", nationality: "United States", height: 188 },
  { playerId: "weiler-babb-nick", name: "Nick Weiler-Babb", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "SG", nationality: "United States", height: 196 },
  { playerId: "cordinier-isaia", name: "Isaia Cordinier", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "SG", nationality: "France", height: 198 },
  { playerId: "dozier-pj", name: "PJ Dozier", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "SG", nationality: "United States", height: 196 },
  { playerId: "smits-rolands", name: "Rolands Smits", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "PF", nationality: "Latvia", height: 213 },
  { playerId: "swider-cole", name: "Cole Swider", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "SF", nationality: "United States", height: 206 },
  { playerId: "osmani-ercan", name: "Ercan Osmani", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "PF", nationality: "North Macedonia", height: 206 },
  { playerId: "papagiannis-georgios", name: "Georgios Papagiannis", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "C", nationality: "Greece", height: 221 },
  { playerId: "dessert-brice", name: "Brice Dessert", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "C", nationality: "France", height: 211 },
  { playerId: "poirier-vincent", name: "Vincent Poirier", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "C", nationality: "France", height: 213 },
  { playerId: "jones-kai", name: "Kai Jones", team: "Anadolu Efes Istanbul", teamCode: "EFS", position: "C", nationality: "United States", height: 213 },
  // AS MONACO
  { playerId: "james-mike", name: "Mike James", team: "AS Monaco", teamCode: "ASM", position: "PG", nationality: "United States", height: 185 },
  { playerId: "okobo-elie", name: "Elie Okobo", team: "AS Monaco", teamCode: "ASM", position: "PG", nationality: "France", height: 191 },
  { playerId: "strazel-matthew", name: "Matthew Strazel", team: "AS Monaco", teamCode: "ASM", position: "PG", nationality: "France", height: 182 },
  { playerId: "nedovic-nemanja", name: "Nemanja Nedovic", team: "AS Monaco", teamCode: "ASM", position: "SG", nationality: "Serbia", height: 192 },
  { playerId: "tarpey-terry", name: "Terry Tarpey", team: "AS Monaco", teamCode: "ASM", position: "SG", nationality: "United States", height: 195 },
  { playerId: "diallo-alpha", name: "Alpha Diallo", team: "AS Monaco", teamCode: "ASM", position: "SF", nationality: "France", height: 201 },
  { playerId: "begarin-juhann", name: "Juhann Begarin", team: "AS Monaco", teamCode: "ASM", position: "SF", nationality: "France", height: 196 },
  { playerId: "blossomgame-jaron", name: "Jaron Blossomgame", team: "AS Monaco", teamCode: "ASM", position: "SF", nationality: "United States", height: 200 },
  { playerId: "mirotic-nikola", name: "Nikola Mirotic", team: "AS Monaco", teamCode: "ASM", position: "PF", nationality: "Spain", height: 208 },
  { playerId: "theis-daniel", name: "Daniel Theis", team: "AS Monaco", teamCode: "ASM", position: "C", nationality: "Germany", height: 204 },
  { playerId: "hayes-kevarrius", name: "Kevarrius Hayes", team: "AS Monaco", teamCode: "ASM", position: "C", nationality: "United States", height: 206 },
  // CRVENA ZVEZDA
  { playerId: "miller-mcintyre-codi", name: "Codi Miller-McIntyre", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "PG", nationality: "United States", height: 191 },
  { playerId: "butler-jared", name: "Jared Butler", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "PG", nationality: "United States", height: 191 },
  { playerId: "canaan-isaiah", name: "Isaiah Canaan", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "SG", nationality: "United States", height: 183 },
  { playerId: "dobric-ognjen", name: "Ognjen Dobric", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "SG", nationality: "Serbia", height: 200 },
  { playerId: "dos-santos-yago", name: "Yago Dos Santos", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "PG", nationality: "Brazil", height: 178 },
  { playerId: "moneke-chima", name: "Chima Moneke", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "PF", nationality: "Nigeria", height: 198 },
  { playerId: "nwora-jordan", name: "Jordan Nwora", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "SF", nationality: "United States", height: 203 },
  { playerId: "kalinic-nikola", name: "Nikola Kalinic", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "SF", nationality: "Serbia", height: 202 },
  { playerId: "ojeleye-semi", name: "Semi Ojeleye", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "PF", nationality: "United States", height: 201 },
  { playerId: "davidovac-dejan", name: "Dejan Davidovac", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "SF", nationality: "Serbia", height: 203 },
  { playerId: "bolomboy-joel", name: "Joel Bolomboy", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "C", nationality: "France", height: 206 },
  { playerId: "izundu-ebuka", name: "Ebuka Izundu", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "C", nationality: "Nigeria", height: 208 },
  { playerId: "rivero-jasiel", name: "Jasiel Rivero", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "C", nationality: "Venezuela", height: 206 },
  { playerId: "motiejunas-donatas", name: "Donatas Motiejunas", team: "Crvena Zvezda Belgrade", teamCode: "CZV", position: "C", nationality: "Lithuania", height: 213 },
  // DUBAI BASKETBALL
  { playerId: "wright-mckinley", name: "McKinley Wright IV", team: "Dubai Basketball", teamCode: "DUB", position: "PG", nationality: "United States", height: 180 },
  { playerId: "avramovic-aleksa", name: "Aleksa Avramovic", team: "Dubai Basketball", teamCode: "DUB", position: "PG", nationality: "Serbia", height: 193 },
  { playerId: "kondic-kosta", name: "Kosta Kondic", team: "Dubai Basketball", teamCode: "DUB", position: "PG", nationality: "Serbia", height: 191 },
  { playerId: "ellis-boogie", name: "Boogie Ellis", team: "Dubai Basketball", teamCode: "DUB", position: "SG", nationality: "United States", height: 193 },
  { playerId: "prepelic-klemen", name: "Klemen Prepelic", team: "Dubai Basketball", teamCode: "DUB", position: "SG", nationality: "Slovenia", height: 191 },
  { playerId: "bacon-dwayne", name: "Dwayne Bacon", team: "Dubai Basketball", teamCode: "DUB", position: "SF", nationality: "United States", height: 198 },
  { playerId: "anderson-justin", name: "Justin Anderson", team: "Dubai Basketball", teamCode: "DUB", position: "SF", nationality: "United States", height: 198 },
  { playerId: "abass-awudu", name: "Awudu Abass", team: "Dubai Basketball", teamCode: "DUB", position: "SF", nationality: "Italy", height: 198 },
  { playerId: "musa-dzanan", name: "Dzanan Musa", team: "Dubai Basketball", teamCode: "DUB", position: "SF", nationality: "Bosnia and Herzegovina", height: 205 },
  { playerId: "bertans-davis", name: "Davis Bertans", team: "Dubai Basketball", teamCode: "DUB", position: "PF", nationality: "Latvia", height: 208 },
  { playerId: "petrusev-filip", name: "Filip Petrusev", team: "Dubai Basketball", teamCode: "DUB", position: "PF", nationality: "Serbia", height: 211 },
  { playerId: "kabengele-mfiondu", name: "Mfiondu Kabengele", team: "Dubai Basketball", teamCode: "DUB", position: "C", nationality: "Canada", height: 207 },
  { playerId: "kamenjas-kenan", name: "Kenan Kamenjas", team: "Dubai Basketball", teamCode: "DUB", position: "C", nationality: "Bosnia and Herzegovina", height: 207 },
  { playerId: "caboclo-bruno", name: "Bruno Caboclo", team: "Dubai Basketball", teamCode: "DUB", position: "C", nationality: "Brazil", height: 208 },
  // EA7 MILAN
  { playerId: "guduric-marko", name: "Marko Guduric", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "SG", nationality: "Serbia", height: 196 },
  { playerId: "brown-lorenzo", name: "Lorenzo Brown", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "PG", nationality: "United States", height: 196 },
  { playerId: "mannion-nico", name: "Nico Mannion", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "PG", nationality: "Italy", height: 190 },
  { playerId: "brooks-armoni", name: "Armoni Brooks", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "SG", nationality: "United States", height: 191 },
  { playerId: "tonut-stefano", name: "Stefano Tonut", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "SG", nationality: "Italy", height: 194 },
  { playerId: "bolmaro-leandro", name: "Leandro Bolmaro", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "SG", nationality: "Argentina", height: 198 },
  { playerId: "leday-zach", name: "Zach LeDay", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "PF", nationality: "United States", height: 202 },
  { playerId: "shields-shavon", name: "Shavon Shields", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "SF", nationality: "United States", height: 201 },
  { playerId: "ricci-giampaolo", name: "Giampaolo Ricci", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "PF", nationality: "Italy", height: 201 },
  { playerId: "booker-devin-mil", name: "Devin Booker", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "C", nationality: "United States", height: 205 },
  { playerId: "nebo-josh", name: "Josh Nebo", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "C", nationality: "United States", height: 207 },
  { playerId: "dunston-bryant", name: "Bryant Dunston", team: "EA7 Emporio Armani Milan", teamCode: "EA7", position: "C", nationality: "United States", height: 203 },
  // FC BARCELONA
  { playerId: "punter-kevin", name: "Kevin Punter", team: "FC Barcelona", teamCode: "BAR", position: "SG", nationality: "United States", height: 193 },
  { playerId: "satoransky-tomas", name: "Tomas Satoransky", team: "FC Barcelona", teamCode: "BAR", position: "PG", nationality: "Czech Republic", height: 201 },
  { playerId: "laprovittola-nicolas", name: "Nicolas Laprovittola", team: "FC Barcelona", teamCode: "BAR", position: "PG", nationality: "Argentina", height: 190 },
  { playerId: "brizuela-dario", name: "Dario Brizuela", team: "FC Barcelona", teamCode: "BAR", position: "SG", nationality: "Spain", height: 188 },
  { playerId: "shengelia-tornike", name: "Tornike Shengelia", team: "FC Barcelona", teamCode: "BAR", position: "PF", nationality: "Georgia", height: 206 },
  { playerId: "clyburn-will", name: "Will Clyburn", team: "FC Barcelona", teamCode: "BAR", position: "SF", nationality: "United States", height: 201 },
  { playerId: "parra-joel", name: "Joel Parra", team: "FC Barcelona", teamCode: "BAR", position: "SF", nationality: "Spain", height: 202 },
  { playerId: "cale-myles", name: "Myles Cale", team: "FC Barcelona", teamCode: "BAR", position: "SF", nationality: "United States", height: 198 },
  { playerId: "hernangomez-willy", name: "Willy Hernangomez", team: "FC Barcelona", teamCode: "BAR", position: "C", nationality: "Spain", height: 211 },
  { playerId: "vesely-jan", name: "Jan Vesely", team: "FC Barcelona", teamCode: "BAR", position: "C", nationality: "Czech Republic", height: 213 },
  { playerId: "fall-youssoupha", name: "Youssoupha Fall", team: "FC Barcelona", teamCode: "BAR", position: "C", nationality: "Senegal", height: 223 },
  // FC BAYERN MUNICH
  { playerId: "obst-andreas", name: "Andreas Obst", team: "FC Bayern Munich", teamCode: "BAY", position: "SG", nationality: "Germany", height: 193 },
  { playerId: "jovic-stefan", name: "Stefan Jovic", team: "FC Bayern Munich", teamCode: "BAY", position: "PG", nationality: "Serbia", height: 196 },
  { playerId: "rathan-mayes-xavier", name: "Xavier Rathan-Mayes", team: "FC Bayern Munich", teamCode: "BAY", position: "PG", nationality: "Canada", height: 193 },
  { playerId: "dimitrijevic-nenad", name: "Nenad Dimitrijevic", team: "FC Bayern Munich", teamCode: "BAY", position: "PG", nationality: "Serbia", height: 191 },
  { playerId: "hollatz-justus", name: "Justus Hollatz", team: "FC Bayern Munich", teamCode: "BAY", position: "PG", nationality: "Germany", height: 194 },
  { playerId: "jessup-justinian", name: "Justinian Jessup", team: "FC Bayern Munich", teamCode: "BAY", position: "SF", nationality: "United States", height: 198 },
  { playerId: "mike-isiaha", name: "Isiaha Mike", team: "FC Bayern Munich", teamCode: "BAY", position: "SF", nationality: "Canada", height: 202 },
  { playerId: "lucic-vladimir", name: "Vladimir Lucic", team: "FC Bayern Munich", teamCode: "BAY", position: "SF", nationality: "Serbia", height: 204 },
  { playerId: "giffey-niels", name: "Niels Giffey", team: "FC Bayern Munich", teamCode: "BAY", position: "SF", nationality: "Germany", height: 200 },
  { playerId: "da-silva-oscar", name: "Oscar da Silva", team: "FC Bayern Munich", teamCode: "BAY", position: "PF", nationality: "Germany", height: 206 },
  { playerId: "gabriel-wenyen", name: "Wenyen Gabriel", team: "FC Bayern Munich", teamCode: "BAY", position: "C", nationality: "United States", height: 206 },
  { playerId: "voigtmann-johannes", name: "Johannes Voigtmann", team: "FC Bayern Munich", teamCode: "BAY", position: "C", nationality: "Germany", height: 211 },
  { playerId: "mccormack-david", name: "David McCormack", team: "FC Bayern Munich", teamCode: "BAY", position: "C", nationality: "United States", height: 208 },
  { playerId: "kratzer-leon", name: "Leon Kratzer", team: "FC Bayern Munich", teamCode: "BAY", position: "C", nationality: "Germany", height: 212 },
  // FENERBAHCE
  { playerId: "baldwin-wade", name: "Wade Baldwin IV", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "PG", nationality: "United States", height: 193 },
  { playerId: "horton-tucker-talen", name: "Talen Horton-Tucker", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "SG", nationality: "United States", height: 193 },
  { playerId: "de-colo-nando", name: "Nando De Colo", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "PG", nationality: "France", height: 193 },
  { playerId: "hall-devon", name: "Devon Hall", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "SG", nationality: "United States", height: 188 },
  { playerId: "zagars-arturs", name: "Arturs Zagars", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "PG", nationality: "Latvia", height: 190 },
  { playerId: "boston-brandon", name: "Brandon Boston Jr.", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "SG", nationality: "United States", height: 198 },
  { playerId: "wilbekin-scottie", name: "Scottie Wilbekin", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "PG", nationality: "United States", height: 188 },
  { playerId: "biberovic-tarik", name: "Tarik Biberovic", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "SF", nationality: "Bosnia and Herzegovina", height: 201 },
  { playerId: "jantunen-mikael", name: "Mikael Jantunen", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "SF", nationality: "Finland", height: 202 },
  { playerId: "colson-bonzie", name: "Bonzie Colson", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "PF", nationality: "United States", height: 198 },
  { playerId: "bitim-onuralp", name: "Onuralp Bitim", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "SF", nationality: "Turkey", height: 196 },
  { playerId: "melli-nicolo", name: "Nicolo Melli", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "C", nationality: "Italy", height: 206 },
  { playerId: "birch-khem", name: "Khem Birch", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "C", nationality: "Canada", height: 206 },
  { playerId: "bacot-armando", name: "Armando Bacot", team: "Fenerbahce Beko Istanbul", teamCode: "FBB", position: "C", nationality: "United States", height: 208 },
  // HAPOEL TEL AVIV
  { playerId: "micic-vasilije", name: "Vasilije Micic", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "PG", nationality: "Serbia", height: 196 },
  { playerId: "bryant-elijah", name: "Elijah Bryant", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "SG", nationality: "United States", height: 196 },
  { playerId: "blakeney-antonio", name: "Antonio Blakeney", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "SG", nationality: "United States", height: 193 },
  { playerId: "jones-chris", name: "Chris Jones", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "PG", nationality: "United States", height: 188 },
  { playerId: "malcolm-collin", name: "Collin Malcolm", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "SF", nationality: "United States", height: 200 },
  { playerId: "ginat-tomer", name: "Tomer Ginat", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "PF", nationality: "Israel", height: 205 },
  { playerId: "wainright-ish", name: "Ish Wainright", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "SF", nationality: "United States", height: 196 },
  { playerId: "motley-johnathan", name: "Johnathan Motley", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "C", nationality: "United States", height: 206 },
  { playerId: "oturu-daniel", name: "Daniel Oturu", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "C", nationality: "United States", height: 208 },
  { playerId: "odiase-tai", name: "Tai Odiase", team: "Hapoel IBI Tel Aviv", teamCode: "MTA", position: "C", nationality: "United States", height: 206 },
  // BASKONIA
  { playerId: "howard-markus", name: "Markus Howard", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "PG", nationality: "United States", height: 180 },
  { playerId: "forrest-trent", name: "Trent Forrest", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "PG", nationality: "United States", height: 191 },
  { playerId: "simmons-kobi", name: "Kobi Simmons", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "PG", nationality: "United States", height: 191 },
  { playerId: "nowell-markquis", name: "Markquis Nowell", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "PG", nationality: "United States", height: 175 },
  { playerId: "spagnolo-matteo", name: "Matteo Spagnolo", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "PG", nationality: "Italy", height: 193 },
  { playerId: "luwawu-cabarrot-timothe", name: "Timothe Luwawu-Cabarrot", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "SF", nationality: "France", height: 196 },
  { playerId: "sedekerskis-tadas", name: "Tadas Sedekerskis", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "SF", nationality: "Lithuania", height: 203 },
  { playerId: "kurucs-rodions", name: "Rodions Kurucs", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "SF", nationality: "Latvia", height: 201 },
  { playerId: "radzevicius-gytis", name: "Gytis Radzevicius", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "SF", nationality: "Lithuania", height: 200 },
  { playerId: "diakite-mamadi", name: "Mamadi Diakite", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "PF", nationality: "United States", height: 206 },
  { playerId: "omoruyi-eugene", name: "Eugene Omoruyi", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "C", nationality: "Nigeria", height: 201 },
  { playerId: "diop-khalifa", name: "Khalifa Diop", team: "Baskonia Vitoria-Gasteiz", teamCode: "BKN", position: "C", nationality: "Senegal", height: 213 },
  // ASVEL
  { playerId: "watson-glynn", name: "Glynn Watson Jr.", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "PG", nationality: "United States", height: 183 },
  { playerId: "heurtel-thomas", name: "Thomas Heurtel", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "PG", nationality: "France", height: 191 },
  { playerId: "harrison-shaquille", name: "Shaquille Harrison", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "SG", nationality: "United States", height: 193 },
  { playerId: "jackson-edwin", name: "Edwin Jackson", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "SG", nationality: "France", height: 190 },
  { playerId: "angola-braian", name: "Braian Angola", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "SG", nationality: "Colombia", height: 196 },
  { playerId: "seljaas-zac", name: "Zac Seljaas", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "SF", nationality: "United States", height: 203 },
  { playerId: "lighty-david", name: "David Lighty", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "SF", nationality: "United States", height: 195 },
  { playerId: "eboua-paul", name: "Paul Eboua", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "SF", nationality: "Cameroon", height: 200 },
  { playerId: "ndiaye-mbaye", name: "Mbaye Ndiaye", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "PF", nationality: "France", height: 203 },
  { playerId: "traore-armel", name: "Armel Traore", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "C", nationality: "France", height: 203 },
  { playerId: "vautier-bastien", name: "Bastien Vautier", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "C", nationality: "France", height: 210 },
  { playerId: "massa-bodian", name: "Bodian Massa", team: "LDLC ASVEL Villeurbanne", teamCode: "ASV", position: "C", nationality: "Senegal", height: 210 },
  // MACCABI
  { playerId: "lundberg-gabriel", name: "Gabriel Lundberg", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "PG", nationality: "Denmark", height: 191 },
  { playerId: "walker-lonnie", name: "Lonnie Walker IV", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "SG", nationality: "United States", height: 196 },
  { playerId: "blatt-tamir", name: "Tamir Blatt", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "PG", nationality: "Israel", height: 188 },
  { playerId: "clark-jimmy", name: "Jimmy Clark III", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "PG", nationality: "United States", height: 191 },
  { playerId: "dowtin-jeffrey", name: "Jeffrey Dowtin Jr.", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "PG", nationality: "United States", height: 185 },
  { playerId: "dibartolomeo-john", name: "John DiBartolomeo", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "PG", nationality: "Australia", height: 183 },
  { playerId: "hoard-jaylen", name: "Jaylen Hoard", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "PF", nationality: "France", height: 206 },
  { playerId: "sorkin-roman", name: "Roman Sorkin", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "SF", nationality: "Israel", height: 203 },
  { playerId: "brissett-oshae", name: "O'Shae Brissett", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "SF", nationality: "Canada", height: 201 },
  { playerId: "rayman-will", name: "Will Rayman", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "SF", nationality: "Israel", height: 201 },
  { playerId: "santos-marcio", name: "Marcio Santos", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "C", nationality: "Brazil", height: 213 },
  { playerId: "leaf-tj", name: "TJ Leaf", team: "Maccabi Rapyd Tel Aviv", teamCode: "MTA", position: "C", nationality: "United States", height: 208 },
  // OLYMPIACOS
  { playerId: "walkup-thomas", name: "Thomas Walkup", team: "Olympiacos Piraeus", teamCode: "OLY", position: "PG", nationality: "Greece", height: 191 },
  { playerId: "ntilikina-frank", name: "Frank Ntilikina", team: "Olympiacos Piraeus", teamCode: "OLY", position: "PG", nationality: "France", height: 196 },
  { playerId: "dorsey-tyler", name: "Tyler Dorsey", team: "Olympiacos Piraeus", teamCode: "OLY", position: "SG", nationality: "Greece", height: 191 },
  { playerId: "larentzakis-giannoulis", name: "Giannoulis Larentzakis", team: "Olympiacos Piraeus", teamCode: "OLY", position: "SG", nationality: "Greece", height: 193 },
  { playerId: "morris-monte", name: "Monte Morris", team: "Olympiacos Piraeus", teamCode: "OLY", position: "PG", nationality: "United States", height: 185 },
  { playerId: "joseph-cory", name: "Cory Joseph", team: "Olympiacos Piraeus", teamCode: "OLY", position: "PG", nationality: "Canada", height: 188 },
  { playerId: "fournier-evan", name: "Evan Fournier", team: "Olympiacos Piraeus", teamCode: "OLY", position: "SG", nationality: "France", height: 201 },
  { playerId: "mckissic-shaquielle", name: "Shaquielle McKissic", team: "Olympiacos Piraeus", teamCode: "OLY", position: "SG", nationality: "United States", height: 191 },
  { playerId: "vezenkov-sasha", name: "Sasha Vezenkov", team: "Olympiacos Piraeus", teamCode: "OLY", position: "SF", nationality: "Bulgaria", height: 206 },
  { playerId: "papanikolaou-kostas", name: "Kostas Papanikolaou", team: "Olympiacos Piraeus", teamCode: "OLY", position: "SF", nationality: "Greece", height: 203 },
  { playerId: "peters-alec", name: "Alec Peters", team: "Olympiacos Piraeus", teamCode: "OLY", position: "PF", nationality: "United States", height: 206 },
  { playerId: "ward-tyson", name: "Tyson Ward", team: "Olympiacos Piraeus", teamCode: "OLY", position: "SF", nationality: "United States", height: 198 },
  { playerId: "milutinov-nikola", name: "Nikola Milutinov", team: "Olympiacos Piraeus", teamCode: "OLY", position: "C", nationality: "Serbia", height: 216 },
  { playerId: "jones-tyrique", name: "Tyrique Jones", team: "Olympiacos Piraeus", teamCode: "OLY", position: "C", nationality: "United States", height: 208 },
  { playerId: "hall-donta", name: "Donta Hall", team: "Olympiacos Piraeus", teamCode: "OLY", position: "C", nationality: "United States", height: 206 },
  { playerId: "fall-moustapha", name: "Moustapha Fall", team: "Olympiacos Piraeus", teamCode: "OLY", position: "C", nationality: "Senegal", height: 221 },
  // PANATHINAIKOS
  { playerId: "nunn-kendrick", name: "Kendrick Nunn", team: "Panathinaikos Athens", teamCode: "PAO", position: "SG", nationality: "United States", height: 195 },
  { playerId: "grant-jerian", name: "Jerian Grant", team: "Panathinaikos Athens", teamCode: "PAO", position: "PG", nationality: "United States", height: 193 },
  { playerId: "shorts-tj", name: "TJ Shorts", team: "Panathinaikos Athens", teamCode: "PAO", position: "PG", nationality: "United States", height: 175 },
  { playerId: "sloukas-kostas", name: "Kostas Sloukas", team: "Panathinaikos Athens", teamCode: "PAO", position: "PG", nationality: "Greece", height: 190 },
  { playerId: "toliopoulos-vassilis", name: "Vassilis Toliopoulos", team: "Panathinaikos Athens", teamCode: "PAO", position: "SG", nationality: "Greece", height: 187 },
  { playerId: "osman-cedi", name: "Cedi Osman", team: "Panathinaikos Athens", teamCode: "PAO", position: "SF", nationality: "Turkey", height: 200 },
  { playerId: "hayes-davis-nigel", name: "Nigel Hayes-Davis", team: "Panathinaikos Athens", teamCode: "PAO", position: "SF", nationality: "United States", height: 203 },
  { playerId: "hernangomez-juancho", name: "Juancho Hernangomez", team: "Panathinaikos Athens", teamCode: "PAO", position: "PF", nationality: "Spain", height: 206 },
  { playerId: "rogkavopoulos-nikos", name: "Nikos Rogkavopoulos", team: "Panathinaikos Athens", teamCode: "PAO", position: "SF", nationality: "Greece", height: 203 },
  { playerId: "mitoglou-konstantinos", name: "Konstantinos Mitoglou", team: "Panathinaikos Athens", teamCode: "PAO", position: "PF", nationality: "Greece", height: 210 },
  { playerId: "lessort-mathias", name: "Mathias Lessort", team: "Panathinaikos Athens", teamCode: "PAO", position: "C", nationality: "France", height: 206 },
  { playerId: "faried-kenneth", name: "Kenneth Faried", team: "Panathinaikos Athens", teamCode: "PAO", position: "C", nationality: "United States", height: 202 },
  { playerId: "holmes-richaun", name: "Richaun Holmes", team: "Panathinaikos Athens", teamCode: "PAO", position: "C", nationality: "United States", height: 206 },
  // PARIS BASKETBALL
  { playerId: "hifi-nadir", name: "Nadir Hifi", team: "Paris Basketball", teamCode: "PAR", position: "SG", nationality: "France", height: 188 },
  { playerId: "robinson-justin", name: "Justin Robinson", team: "Paris Basketball", teamCode: "PAR", position: "PG", nationality: "United States", height: 173 },
  { playerId: "rhoden-jared", name: "Jared Rhoden", team: "Paris Basketball", teamCode: "PAR", position: "SG", nationality: "United States", height: 196 },
  { playerId: "ouattara-yakuba", name: "Yakuba Ouattara", team: "Paris Basketball", teamCode: "PAR", position: "SG", nationality: "France", height: 192 },
  { playerId: "herrera-sebastian", name: "Sebastian Herrera", team: "Paris Basketball", teamCode: "PAR", position: "PG", nationality: "Venezuela", height: 185 },
  { playerId: "cavaliere-leopold", name: "Leopold Cavaliere", team: "Paris Basketball", teamCode: "PAR", position: "PF", nationality: "France", height: 202 },
  { playerId: "hommes-daulton", name: "Daulton Hommes", team: "Paris Basketball", teamCode: "PAR", position: "SF", nationality: "United States", height: 203 },
  { playerId: "mbaye-amath", name: "Amath M'Baye", team: "Paris Basketball", teamCode: "PAR", position: "PF", nationality: "Senegal", height: 203 },
  { playerId: "morgan-jeremy", name: "Jeremy Morgan", team: "Paris Basketball", teamCode: "PAR", position: "SF", nationality: "United States", height: 199 },
  { playerId: "willis-derek", name: "Derek Willis", team: "Paris Basketball", teamCode: "PAR", position: "PF", nationality: "United States", height: 205 },
  { playerId: "dokossi-allan", name: "Allan Dokossi", team: "Paris Basketball", teamCode: "PAR", position: "C", nationality: "France", height: 203 },
  { playerId: "faye-mouhamed", name: "Mouhamed Faye", team: "Paris Basketball", teamCode: "PAR", position: "C", nationality: "Senegal", height: 205 },
  // PARTIZAN
  { playerId: "jones-carlik", name: "Carlik Jones", team: "Partizan Belgrade", teamCode: "PAR", position: "PG", nationality: "United States", height: 188 },
  { playerId: "milton-shake", name: "Shake Milton", team: "Partizan Belgrade", teamCode: "PAR", position: "SG", nationality: "United States", height: 196 },
  { playerId: "washington-duane", name: "Duane Washington", team: "Partizan Belgrade", teamCode: "PAR", position: "SG", nationality: "United States", height: 191 },
  { playerId: "calathes-nick", name: "Nick Calathes", team: "Partizan Belgrade", teamCode: "PAR", position: "PG", nationality: "Greece", height: 200 },
  { playerId: "payne-cameron", name: "Cameron Payne", team: "Partizan Belgrade", teamCode: "PAR", position: "PG", nationality: "United States", height: 188 },
  { playerId: "marinkovic-vanja", name: "Vanja Marinkovic", team: "Partizan Belgrade", teamCode: "PAR", position: "SG", nationality: "Serbia", height: 196 },
  { playerId: "bonga-isaac", name: "Isaac Bonga", team: "Partizan Belgrade", teamCode: "PAR", position: "SF", nationality: "Germany", height: 201 },
  { playerId: "brown-sterling", name: "Sterling Brown", team: "Partizan Belgrade", teamCode: "PAR", position: "SF", nationality: "United States", height: 196 },
  { playerId: "muurinen-miikka", name: "Miikka Muurinen", team: "Partizan Belgrade", teamCode: "PAR", position: "SF", nationality: "Finland", height: 203 },
  { playerId: "pokusevski-aleksej", name: "Aleksej Pokusevski", team: "Partizan Belgrade", teamCode: "PAR", position: "PF", nationality: "Serbia", height: 216 },
  { playerId: "lauvergne-joffrey", name: "Joffrey Lauvergne", team: "Partizan Belgrade", teamCode: "PAR", position: "PF", nationality: "France", height: 211 },
  { playerId: "fernando-bruno", name: "Bruno Fernando", team: "Partizan Belgrade", teamCode: "PAR", position: "C", nationality: "Angola", height: 206 },
  { playerId: "osetkowski-dylan", name: "Dylan Osetkowski", team: "Partizan Belgrade", teamCode: "PAR", position: "C", nationality: "United States", height: 206 },
  { playerId: "jekiri-tonye", name: "Tonye Jekiri", team: "Partizan Belgrade", teamCode: "PAR", position: "C", nationality: "Nigeria", height: 211 },
  // REAL MADRID
  { playerId: "campazzo-facundo", name: "Facundo Campazzo", team: "Real Madrid", teamCode: "RMB", position: "PG", nationality: "Argentina", height: 178 },
  { playerId: "llull-sergio", name: "Sergio Llull", team: "Real Madrid", teamCode: "RMB", position: "PG", nationality: "Spain", height: 190 },
  { playerId: "maledon-theo", name: "Theo Maledon", team: "Real Madrid", teamCode: "RMB", position: "PG", nationality: "France", height: 193 },
  { playerId: "abalde-alberto", name: "Alberto Abalde", team: "Real Madrid", teamCode: "RMB", position: "SG", nationality: "Spain", height: 202 },
  { playerId: "feliz-andres", name: "Andres Feliz", team: "Real Madrid", teamCode: "RMB", position: "SG", nationality: "Dominican Republic", height: 188 },
  { playerId: "hezonja-mario", name: "Mario Hezonja", team: "Real Madrid", teamCode: "RMB", position: "SF", nationality: "Croatia", height: 206 },
  { playerId: "deck-gabriel", name: "Gabriel Deck", team: "Real Madrid", teamCode: "RMB", position: "SF", nationality: "Argentina", height: 198 },
  { playerId: "lyles-trey", name: "Trey Lyles", team: "Real Madrid", teamCode: "RMB", position: "PF", nationality: "United States", height: 206 },
  { playerId: "tavares-walter", name: "Walter Tavares", team: "Real Madrid", teamCode: "RMB", position: "C", nationality: "Cape Verde", height: 221 },
  { playerId: "len-alex", name: "Alex Len", team: "Real Madrid", teamCode: "RMB", position: "C", nationality: "Ukraine", height: 213 },
  { playerId: "garuba-usman", name: "Usman Garuba", team: "Real Madrid", teamCode: "RMB", position: "C", nationality: "Spain", height: 202 },
  { playerId: "okeke-chuma", name: "Chuma Okeke", team: "Real Madrid", teamCode: "RMB", position: "C", nationality: "United States", height: 200 },
  // VALENCIA
  { playerId: "montero-jean", name: "Jean Montero", team: "Valencia Basket", teamCode: "VLC", position: "PG", nationality: "Dominican Republic", height: 188 },
  { playerId: "thompson-darius", name: "Darius Thompson", team: "Valencia Basket", teamCode: "VLC", position: "PG", nationality: "North Macedonia", height: 193 },
  { playerId: "moore-omari", name: "Omari Moore", team: "Valencia Basket", teamCode: "VLC", position: "SG", nationality: "United States", height: 198 },
  { playerId: "puerto-josep", name: "Josep Puerto", team: "Valencia Basket", teamCode: "VLC", position: "SG", nationality: "Spain", height: 199 },
  { playerId: "badio-brancou", name: "Brancou Badio", team: "Valencia Basket", teamCode: "VLC", position: "SG", nationality: "Senegal", height: 193 },
  { playerId: "de-larrea-sergio", name: "Sergio De Larrea", team: "Valencia Basket", teamCode: "VLC", position: "SG", nationality: "Spain", height: 198 },
  { playerId: "taylor-kameron", name: "Kameron Taylor", team: "Valencia Basket", teamCode: "VLC", position: "SF", nationality: "United States", height: 198 },
  { playerId: "key-braxton", name: "Braxton Key", team: "Valencia Basket", teamCode: "VLC", position: "SF", nationality: "United States", height: 201 },
  { playerId: "reuvers-nate", name: "Nate Reuvers", team: "Valencia Basket", teamCode: "VLC", position: "PF", nationality: "United States", height: 211 },
  { playerId: "costello-matthew", name: "Matthew Costello", team: "Valencia Basket", teamCode: "VLC", position: "C", nationality: "United States", height: 206 },
  { playerId: "pradilla-jaime", name: "Jaime Pradilla", team: "Valencia Basket", teamCode: "VLC", position: "C", nationality: "Spain", height: 205 },
  { playerId: "sako-neal", name: "Neal Sako", team: "Valencia Basket", teamCode: "VLC", position: "C", nationality: "France", height: 211 },
  // VIRTUS BOLOGNA
  { playerId: "edwards-carsen", name: "Carsen Edwards", team: "Virtus Bologna", teamCode: "VIR", position: "SG", nationality: "United States", height: 180 },
  { playerId: "vildoza-luca", name: "Luca Vildoza", team: "Virtus Bologna", teamCode: "VIR", position: "PG", nationality: "Argentina", height: 191 },
  { playerId: "pajola-alessandro", name: "Alessandro Pajola", team: "Virtus Bologna", teamCode: "VIR", position: "PG", nationality: "Italy", height: 194 },
  { playerId: "hackett-daniel", name: "Daniel Hackett", team: "Virtus Bologna", teamCode: "VIR", position: "PG", nationality: "Italy", height: 196 },
  { playerId: "morgan-matt", name: "Matt Morgan", team: "Virtus Bologna", teamCode: "VIR", position: "PG", nationality: "United States", height: 188 },
  { playerId: "niang-saliou", name: "Saliou Niang", team: "Virtus Bologna", teamCode: "VIR", position: "SF", nationality: "France", height: 203 },
  { playerId: "alston-derrick", name: "Derrick Alston Jr.", team: "Virtus Bologna", teamCode: "VIR", position: "SF", nationality: "United States", height: 206 },
  { playerId: "jallow-karim", name: "Karim Jallow", team: "Virtus Bologna", teamCode: "VIR", position: "SF", nationality: "Germany", height: 198 },
  { playerId: "smailagic-alen", name: "Alen Smailagic", team: "Virtus Bologna", teamCode: "VIR", position: "C", nationality: "Serbia", height: 208 },
  { playerId: "diouf-mouhamet", name: "Mouhamet Diouf", team: "Virtus Bologna", teamCode: "VIR", position: "C", nationality: "Senegal", height: 206 },
  // ZALGIRIS
  { playerId: "francisco-sylvain", name: "Sylvain Francisco", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "PG", nationality: "France", height: 185 },
  { playerId: "williams-goss-nigel", name: "Nigel Williams-Goss", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "PG", nationality: "United States", height: 191 },
  { playerId: "lo-maodo", name: "Maodo Lo", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "PG", nationality: "Germany", height: 192 },
  { playerId: "sirvydis-deividas", name: "Deividas Sirvydis", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "SG", nationality: "Lithuania", height: 204 },
  { playerId: "giedraitis-dovydas", name: "Dovydas Giedraitis", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "SG", nationality: "Lithuania", height: 193 },
  { playerId: "brazdeikis-ignas", name: "Ignas Brazdeikis", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "SG", nationality: "Canada", height: 201 },
  { playerId: "tubelis-azuolas", name: "Azuolas Tubelis", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "PF", nationality: "Lithuania", height: 208 },
  { playerId: "butkevicius-arnas", name: "Arnas Butkevicius", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "SF", nationality: "Lithuania", height: 197 },
  { playerId: "ulanovas-edgaras", name: "Edgaras Ulanovas", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "PF", nationality: "Lithuania", height: 199 },
  { playerId: "sleva-dustin", name: "Dustin Sleva", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "PF", nationality: "United States", height: 203 },
  { playerId: "wright-moses", name: "Moses Wright", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "C", nationality: "United States", height: 206 },
  { playerId: "birutis-laurynas", name: "Laurynas Birutis", team: "Zalgiris Kaunas", teamCode: "ZAL", position: "C", nationality: "Lithuania", height: 213 },
];

async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("Connected to MongoDB");

  let count = 0;
  for (const p of players) {
    await Player.findOneAndUpdate(
      { playerId: p.playerId },
      { $set: { ...p, active: true } },
      { upsert: true }
    );
    count++;
  }

  console.log(`Done — ${count} players upserted.`);
  await mongoose.disconnect();
}

main().catch((err) => { console.error(err); process.exit(1); });